global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'payment-gateway'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['payment-gateway-app:8080']
