# H2 In-memory database configuration (default for development)
spring:
  datasource:
    url: jdbc:h2:mem:paymentdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        "[format_sql]": true
        "[show_sql]": true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    baselineOnMigrate: true
